services:
  - type: web
    name: flowlite-test-instance
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/flows
    envVars:
      - key: FLOWLITE_SHOWCASE_INITIAL_SEED_COUNT
        value: "100"
      - key: FLOWLITE_SHOWCASE_REPEAT_SEEDING_ENABLED
        value: "false"
